import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Polyfill for `__dirname` in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const generationNote = `// This file was auto generated by the 'generateJsonObjectTypes.js' script\n\n`;

const configPath = process.argv[2];
if (!configPath) {
    console.error("Please provide the path to RTK OpenAPI configuration file.");
    process.exit(1);
}

const argOutFilePath = process.argv[3];
if (!argOutFilePath) {
    console.error("Please provide the output file path.");
    process.exit(1);
}

const rtkConfigFile = path.resolve(__dirname, configPath)
const rtkConfig = fs.readFileSync(rtkConfigFile, 'utf-8');
const rtkConfigJSON = JSON.parse(rtkConfig);

if (!Object.hasOwn(rtkConfigJSON, 'outputFile')) {
    console.error("The RTK OpenAPI configuration does not have an outputFile attribute specified.");
    process.exit(1);
}
const apiOutputFile = rtkConfigJSON['outputFile'];

const fullApiFilePath = path.resolve("src/project", apiOutputFile);
const outputFilePath = path.resolve(__dirname, argOutFilePath);

const fileContent = fs.readFileSync(fullApiFilePath, 'utf8');

const typeRegex = /type:\s"([^"]*)"/g;
const match = [...fileContent.match(typeRegex)];

if (match) {
    const types = match.map(m => m.replace(/type:\s"/g, '')
        .replace(/"/g, '')).map(m => `${m.replaceAll(/'/g, "")} = "${m}"`);
    const objectTypes = `${generationNote}export enum JsonObjectType {\n${types.sort().join(',\n')}\n}\n`;

    console.log("Generating JSON object types");

    fs.writeFileSync(outputFilePath, objectTypes);
    console.log(`JSON object types extracted to ${outputFilePath}`);
} else {
    console.error('JSON object types definition not found.');
}
