import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Polyfill for `__dirname` in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const configPath = process.argv[2];
if (!configPath) {
    console.error("Please provide the path to RTK OpenAPI configuration file.");
    process.exit(1);
}

const argOutFilePath = process.argv[3];
if (!argOutFilePath) {
    console.error("Please provide the Roles output file path.");
    process.exit(1);
}

const rtkConfigFile = path.resolve(__dirname, configPath)
const rtkConfig = fs.readFileSync(rtkConfigFile, 'utf-8');
const rtkConfigJSON = JSON.parse(rtkConfig);

if (!Object.hasOwn(rtkConfigJSON, 'outputFile')) {
    console.error("The RTK OpenAPI configuration does not have an outputFile attribute specified.");
    process.exit(1);
}
const apiOutputFile = rtkConfigJSON['outputFile'];

const fullApiFilePath = path.resolve("src/project", apiOutputFile);
const rolesOutputFilePath = path.resolve(__dirname, argOutFilePath);

const fileContent = fs.readFileSync(fullApiFilePath, 'utf8');

const userRoleRegex = /userRole:\s*([\s\S]*?);/;
const match = fileContent.match(userRoleRegex);

if (match && match[1]) {
    console.log("Generating ", argOutFilePath);
    const roles = match[1]
        .replace(/\s*\|\s*/g, '\n')
        .replace(/"/g, '')
        .split('\n')
        .map(role => role.trim())
        .map(role => role.replace("ROLE_", ""))
        .filter(role => role);
    const generationNote = `// This file was auto generated by the 'generateUserRoles.js' script\n\n`;
    const typeDefinition = `${generationNote}export type Role =\n    | '${roles.sort().join('\'\n    | \'')}'\n`;
    fs.writeFileSync(rolesOutputFilePath, typeDefinition);
    console.log(`Roles extracted to ${rolesOutputFilePath}`);
} else {
    console.error('Role type definition not found.');
}
