// This file was auto generated by the 'generateJsonObjectTypes.js' script

export enum JsonObjectType {
CancelContemptOfCourtNoticeNumberCriteria = "CancelContemptOfCourtNoticeNumberCriteria",
CancelContemptOfCourtWarrantNumberCriteria = "CancelContemptOfCourtWarrantNumberCriteria",
CourtResultNoticeNumberCriteria = "CourtResultNoticeNumberCriteria",
LoadCharge = "LoadCharge",
LoadChargeDto = "LoadChargeDto",
OverloadTransgression = "OverloadTransgression",
OverloadTransgressionDto = "OverloadTransgressionDto",
RtqsCharge = "RtqsCharge",
RtqsChargeDto = "RtqsChargeDto",
RtqsTransgression = "RtqsTransgression",
RtqsTransgressionDto = "RtqsTransgressionDto",
SnapshotLoadCharge = "SnapshotLoadCharge",
SnapshotLoadChargeDto = "SnapshotLoadChargeDto",
SnapshotRtqsCharge = "SnapshotRtqsCharge",
SnapshotRtqsChargeDto = "SnapshotRtqsChargeDto",
SnapshotSpeedCharge = "SnapshotSpeedCharge",
SnapshotSpeedChargeDto = "SnapshotSpeedChargeDto",
SpeedCharge = "SpeedCharge",
SpeedTransgression = "SpeedTransgression"
}
